### ISSUE TITLE
Interoperability with other library - way to check which theme is in use

### ISSUE THREAD

**Issue by pixellos** [virtualvivek/react-windows-ui#11]
Hi, 
As i saw ThemeManger is only setting given color in dom. Maybe there should be callback when it happen?

**Comment by virtualvivek** [comment]
Hi @pixellos ,

I will add `onColorChange` and `onModeChange` listener for `AppTheme` component.
That will be implement soon along with other enhancement !

**Comment by virtualvivek** [comment]
Hi @pixellos ,

I have added the following components:

1. **`AppTheme`** props **`onSchemeChange`** and **``onColorChange``**.
2. Added component **`Appearance`** to **Get** and **Set** themes on runtime.

For more about the usage i will suggest you to see the docs.
