### ISSUE TITLE
NavBar customization

### ISSUE THREAD

**Issue by NuclearInstruments** [virtualvivek/react-windows-ui#12]
Hi,
I'm Andrea. First of all congratulations for the great work!

I would like to ask you if there is any way to hide the Light/Dark switch on the NavBar without modify your code. 
Is there any way to open the NavBar in "mobile mode" (icons only) when the page is opened?

Thank You
Andrea

**Comment by virtualvivek** [comment]
Hi @NuclearInstruments ,

I will suggest you to check the new published version,
I have improved the navbar and now it only has some major component and other components can add externally.

**Comment by NuclearInstruments** [comment]
Dear Vivek,
i tested the new version.
Two point:

1) Version 4.0.4
Adding AppTheme to App.js has no effect and the theme is always light
          <AppTheme
            scheme={'dark'}
            onColorChange={()=> {}}
            onSchemeChange={()=> {}}
          
          />


2) If i try to upgrade the version to one greater than 4.0.4 I got 

Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `App`.
▶ 22 stack frames were collapsed.
Module.<anonymous>
C:/temp/react-windows-ui-boilerplate/src/index.js:8
   5 | import 'react-windows-ui/icons/fonts/fonts.min.css'
   6 | import App from './App'
   7 | 
>  8 | ReactDOM.render(
   9 |   <React.StrictMode>
  10 |     <App />
  11 |   </React.StrictMode>,


to be sure i started from an empty project fro your last Boilerplate https://github.com/virtualvivek/react-windows-ui-boilerplate.git

Thank you
Andrea

**Comment by virtualvivek** [comment]
Hi Andrea aka @NuclearInstruments ,

I have checked in my local machine and you are right AppTheme has no effect on "dark" prop on mount at *App.js*,

also apologies for -v4.0.5 actually for 4.0.5 i forget to import React from 'react' thats why after 10-15 mins of publishing i had to publish another -v4.0.6 but after i got your response, i am working on both boilerplate and repo, and give me some time to publish a more stable and rightfull version. :)

**Comment by virtualvivek** [comment]
Hi @NuclearInstruments ,

I have fixed this issue of **AppTheme** and also updated boilerplate.
This new release removed **TransitionToLeft** component because new version don't require this component so,
You can check the new release at your side and update me whether this issue needs to be closed.

**Comment by andreaabba** [comment]
Hi Vivek,
i tested the new release ad it works perfectly. The theme is applied and there is no more error on load.
Thank you very much
Andrea

**Comment by NuclearInstruments** [comment]
Sorry I replied with my personal github account. I close now the issue.
Thank You
Andrea

**Comment by virtualvivek** [comment]
Hi @andreaabba aka @NuclearInstruments ,

I feel relaxed after listening about no issue in the new release version **-v4.0.8**
Now i am going to release at github this version too!

No Worries....  from where you replied the thing matter is you replied :)
Thanks for contributing to this project also for the navigation part too!
