### ISSUE TITLE
demo page is broken 

### ISSUE THREAD

**Issue by fergusmeiklejohn** [virtualvivek/react-windows-ui#14]
https://virtualvivek.github.io/react-windows-ui/#/

**Comment by virtualvivek** [comment]
Hi @fergusmeiklejohn ,

Can you please cross check cauz its being visible on both on my mobile and laptop.

**Comment by fergusmeiklejohn** [comment]
yeah definitely broken. It's flashes on load then goes white. This is the console error:
<img width="800" alt="Screenshot 2021-11-16 at 8 30 38 PM" src="https://user-images.githubusercontent.com/11864025/141985852-d082f55c-5e36-4ccb-8b4a-bce04d76fd6c.png">

**Comment by virtualvivek** [comment]
#13

**Comment by virtualvivek** [comment]
jlord/sheetsee.js#26

**Comment by virtualvivek** [comment]
#13

**Comment by virtualvivek** [comment]
Closes #13

**Comment by virtualvivek** [comment]
virtualvivek/react-windows-ui#13

**Comment by virtualvivek** [comment]
Hi @fergusmeiklejohn  & @DerGoogler

I didn't realize this before but after getting many such cases,
I am working on resolving the demo page error,

I will notify u when i get something to update

**Comment by virtualvivek** [comment]
Hi @fergusmeiklejohn & @DerGoogler ,

The `demo page error` has been **resolved** and now working,

Can you please check at your side and close this issue.

**Comment by virtualvivek** [comment]
Hi @fergusmeiklejohn ,

Since this issue has been resolved, closing this one,
If still you have any matter regarding the topic above you can open this issue whenever you want.
