### ISSUE TITLE
CommandBar

### ISSUE THREAD

**Issue by zivlakmilos** [virtualvivek/react-windows-ui#15]
I think that having CommandBar like in Fluent library will be great addition to this set of components.

https://developer.microsoft.com/en-us/fluentui#/controls/web/commandbar

I really like this library, but I found that I miss CommandBar.

**Comment by virtualvivek** [comment]
Hi @zivlakmilos ,

Thanks for supporting the lib
actually it has a commandBar but i forget to add the docs about it
Here it is : https://virtualvivek.github.io/react-windows-ui/#/CommandBarLayout

If you get something this this above then i will sure add docs and usage tommorow or
if you need some improvement you can just mention here :)

**Comment by zivlakmilos** [comment]
That's great. Thanks for great work. :)

**Comment by virtualvivek** [comment]
I have also checked the link you shared from microsoft's official docs and i find out that i need to add some more customization to the existing CommandBar component.

thanks for opening the issue ,I find it usefull :)

**Comment by zivlakmilos** [comment]
I found problem with CommandBar component. It's "floating" above content. So content goes behind it and it's not visible. I don't know is that desired behavior. You can see that in Your example, where <h1> tag is not visible.

**Comment by virtualvivek** [comment]
Hi @zivlakmilos ,

Yup the CommandBar default behaviour is floating before but now i realized after seeing ms official CommandBar that our's is not so much productive for now so i am customizing bit more along with its docs.

 :)

**Comment by zivlakmilos** [comment]
Looks good to me. :)
