### ISSUE TITLE
AppTheme onChange props not work

### ISSUE THREAD

**Issue by thevobos** [virtualvivek/react-windows-ui#20]
How can i fix it ? 

```
  <AppTheme
        scheme={"light"}
        onColorChange={() => {alert("as")}}
        onSchemeChange={() => {alert("asa")}}
    />
```

**Comment by virtualvivek** [comment]
Hi @thevobos ,
Could you please share me the version you are using ?

**Comment by thevobos** [comment]
Hi ViVek,

i am use  4.2.0 version and i checked the source code and i saw th e doesn't completed the props the this props operation and after then i looked the your web page and i saw the information about for it props. in my version is not available for using 


thank for your quik reply :)
