### ISSUE TITLE
textarea

### ISSUE THREAD

**Issue by Maicarons2022** [virtualvivek/react-windows-ui#21]
hello developer,

I find the textinput cannot be multi-line. Could you add a textarea?  
thanks a lot!

**Comment by Maicarons2022** [comment]
thanks,I really appreciate your help. You saved my day.

**Comment by virtualvivek** [comment]
Hi @Maicarons2022 ,

you can use a Text Area with below code in any version -

```jsx
<textarea class="app-textarea" placeholder="Input Text Area"></textarea>
```
