### ISSUE TITLE
React-Native Support

### ISSUE THREAD

**Issue by lun4rch** [virtualvivek/react-windows-ui#22]
The library is fascinating, but is it possible to integrate it with the react-native project for desktop?

**Comment by virtualvivek** [comment]
Hi @lun4rch,

Looks like **react-native** for windows uses **_native_** technologies to build platform native apps whereas **react-windows-ui** comes with native like web components that imitate the native look & feel of a native environment but with fully web technology without interfering native architecture.

If you still want to access some of the native features of a native platform you can mix this with **electron** or **tauri**.
