### ISSUE TITLE
JS code to manipulate components

### ISSUE THREAD

**Issue by LeVraiStagiaire** [virtualvivek/react-windows-ui#26]
Hello,
I created a React application with this template and noticed that there was no documentation on component manipulation (eg. retrieving text from a text box) in JS. Could you help me ?
Thank you in advance ;)

**Comment by virtualvivek** [comment]
HI @LeVraiStagiaire,

Thanks for checking this bug on the text fields.
I will be fixing that in the next release with few more improvements and with docs.

**Comment by LeVraiStagiaire** [comment]
Hi @virtualvivek 
Thanks for your answer. Have you planned a date for the next release?

**Comment by LeVraiStagiaire** [comment]
Hi @virtualvivek,

It is on Textboxes

**Comment by virtualvivek** [comment]
Hi @LeVraiStagiaire,

Thanks for your quick response,
Let me check and also will try to add examples/demos for the usage on the docs for the same. :)

**Comment by LeVraiStagiaire** [comment]
Thank you very much !

Le 22 juin 2023 à 15:28, Vivek Verma ***@***.***> a écrit :

﻿

Hi @LeVraiStagiaire<https://github.com/LeVraiStagiaire>,

Thanks for your quick response,
Let me check and also will try to add examples/demos for the usage on the docs for the same. :)

**Comment by virtualvivek** [comment]
Hi @LeVraiStagiaire ,

I have updated the project with additional features including docs to manipulate `TextBoxes`.
