### ISSUE TITLE
There are no type definitions available for use with typescript

### ISSUE THREAD

**Issue by Unluckymichell** [virtualvivek/react-windows-ui#3]
I would like to use these components in a typescript / react project.
(I will do a fork later this week and create the definitions myself)

**Comment by virtualvivek** [comment]
Hi @Unluckymichell ,
Glad to hear that you use react-windows-ui in your project,
I am apologizing for not added `d.ts` files to this project this issue is also pinged by @Myzel394
And now i believe that the `d.ts` files are needed asap.

so stared figuring out creating the files if you are thinking of creating the files please also create a `pull request` we will be happy
or also try it by myself so it can be compatible with typescript project.

**Comment by Myzel394** [comment]
I think it would be better to refactor the jsx files to tsx files now. Otherwise we will be at the same moment as we are now. @virtualvivek

**Comment by virtualvivek** [comment]
HI @Myzel394 , @Unluckymichell ,
I started to create **typing** for the available `.jsx` components
@Myzel394 can it be sufficient for now to use only typings, i have checked few components currently and working great with _VSCode_ and _intelliSense_.

@Myzel394 if you are interested to optimize the `.d.ts` you can also do that. iam on the way completing this file

![tperscripting](https://user-images.githubusercontent.com/54973249/123233628-d629b400-d4f7-11eb-9be8-0dbc901804bb.JPG)

**Comment by Myzel394** [comment]
@virtualvivek Please don't put all definitions in one file. Create a d.ts file for each component. This way you profit from a clean code base :D

**Comment by virtualvivek** [comment]
@Myzel394 yes you are right i forget that in future if we have to edit any component it will become blender to search in a big d.ts file for now will create it for each component seperately.
Thanks for the suggestion.

**Comment by Myzel394** [comment]
Btw, AFAIK "SFC" shouldn't be used, you can simply use "Component" and pass the props as a generic to it

**Comment by virtualvivek** [comment]
it will like this??

```tsx
export interface ButtonProps {
    value?: string;
}
declare const Button: React.Component<ButtonProps>
```

**Comment by Myzel394** [comment]
Exactly, I did it like this
![reactwindowsui.PNG](https://user-images.githubusercontent.com/50424412/123243922-bd170800-d4e3-11eb-89c9-a70384aca046.PNG)

**Comment by virtualvivek** [comment]
Thankyou @Myzel394 for helping me out :smile: 
Regards you both @Unluckymichell and @Myzel394 for pingind for typescripting
maybe it will never added without this pings.

**Comment by Unluckymichell** [comment]
Nice to see this added so fast. If i can still help with any types or if i should update the jsx to tsx files later please tell me.

**Comment by Myzel394** [comment]
@virtualvivek you can also contact me over Matrix @myzel394:matrix.org

**Comment by virtualvivek** [comment]
Hi @Unluckymichell ,
I have added all the type definitions, yes you can help us in many ways,
Can you please see the type definitions and check _everything is fine to be deployed._
You can find speific `.d.ts` files using link: **src/lib/src/components/ComponentName/index.d.ts**

We can close this issue after successful publishing in **npm**.

**Comment by virtualvivek** [comment]
Hi @Myzel394 ,
Sure i can contact you if encountered in any issue. :D
Thankyou in advance.

**Comment by Unluckymichell** [comment]
@virtualvivek See my pull request #4
