### ISSUE TITLE
Some components are missed

### ISSUE THREAD

**Issue by EhsanullahQaderi** [virtualvivek/react-windows-ui#6]
1: grid layout (row, col)
2: multi level menu in side bar 
3: drop-down menu 
4: react-select
5: option menu

The mentioned components will  rise up of the betterment of template

**Comment by virtualvivek** [comment]
HI @EhsanullahQadari ,
We have components that can solve some of your needs
for 
**Option menu** you can use:
```jsx
<SelectBox />
```
for **Drop Down Menu** you can use:
```jsx
<MenuBar />
```

### Addons Needed
 - Multi Level menu bar in **Side Bar**
> Will try to build asap.

 - React Select `as we can add a styled` **`Select`** `component`
 > Will add possibly at next release.

### Grid layout (row, col)

As This library is indented to provide **Components** that as composible and mutable.
> You can wrap **components** according to what best suits to the project.

**Comment by virtualvivek** [comment]
Hi @EhsanullahQaderi ,

I have added some more components:

1: multi level menu in side bar - **`NavBarSubMenu`**
2: drop-down menu - **`MenuBar`**
3: react-select - **`Select`**

I will suggest you to check the docs for the latest version of `react-windows-ui`.
If still have some queries you can open this issue whenever you want :)
