### ISSUE TITLE
Why not make this into a fully fledged UI framwork like Material, antd, chakra, etc

### ISSUE THREAD

**Issue by prik-k** [virtualvivek/react-windows-ui#7]
Vivek, 

Your components deserve much more appreciation than they got. Thanks for making them.

Consider working a bit on the documentation part similar to the popular UIs out there. And after adding some more components soon the community will see it as a major project to use Microsoft's UI style in their project and contribute and use it actively thus more sponsors to support this project. 

Hope I make sense. Thanks

P.S - Include the link to the actual docs at multiple places, In the demo itself and in the readme.md file, It's hard to find.

**Comment by virtualvivek** [comment]
Hi @prik-k ,
Glad to hear from you and your great support for **`react-windows-ui`**,
Yes all your suggestions makes a great sense.
I got the notification about this issue late night yesterday on my mail so,
I started working little bit more on the documentation part and specially trying to adding more **codes and links** to actual docs too.

**Major Changes** was fixing the demo bit more clear for each component to make development more faster for the devs.

Have a look on the below preview. 
I got the inspiration on how to write better docs from **chakra-ui.com** as suggested by you.

**IS IT BETTER ??**

![docs_preview_](https://user-images.githubusercontent.com/54973249/126489591-825a3853-a4a7-44d0-9aaf-4e67e8b29bda.JPG)

**Comment by prik-k** [comment]
Oh I just discovered a little confusing on my part, I initially thought there is another link especially for use and documentation part and a different link for demo purpose. My bad.

Anyways, Yes this definitely looks much better. Would be better if there is more piece of text of explanation but that's completely on you. Will definitely use this UI someday soon. 
You can close the issue now. 

Big Thanks!

**Comment by virtualvivek** [comment]
Hi @prik-k ,
Thankyou for all your advice for improving the docs, maybe I never get the issue if you didn't raise it and as a whole it make the project more clear now.
I will add more text of explanation soon.

I am closing this issue for now.
Regards.

**Comment by virtualvivek** [comment]
Hi @prik-k ,
I pointed out the mistake,
In the demo i added NavBar named as **Links** which looks like the Page with links but was based on the **Component Link**
Thanks for pointing out this misunderstand able issue,
I am fixing this and will be live after few days. :)
