### ISSUE TITLE
Question on license and permissible usage

### ISSUE THREAD

**Issue by rirlswift** [virtualvivek/react-windows-ui#9]
I am DevOps engineer for a small company that makes VTOL drones.
I am thinking I wanted to use this framework for creating a site that allows download and deployment of our embedded software to our drones. 
I understand such a usage as covered by the MIT license.
Can you please let me know if there is something else I need to cover to begin to use your software.

**Comment by virtualvivek** [comment]
Hi @rirlswift ,

Firstly congratulations for your new project on drones !!

"As per the MIT license you can use the code anywhere under your project workflow as long as you include the original copy of the MIT license in their distribution."

But..but..... As Informally i am saying you can use this code anywhere you want, and build cool stuff even in your production builds.
I will never copywrite or disrupt your work.

My main motive to produce this framework is only to ensure developers can build cool windows ui apps without any boundries.

Go ahead bro !!
